pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g typescript@3.7.5
      npm install -g mocha@7.0.1
      npm install -g mocha-junit-reporter
      npm install -g nyc
      npm install
    displayName: "Installing dependencies"

  - script: tsc -p .
    displayName: "Compiling typescript"

  - script: NODE_ENV=test LOG_LEVEL=debug DB_PWD=$(DB_PASSWORD) DB_USER=$(DB_USERNAME) DB_HOST=$(DB_HOST) DB_NAME=$(DB_NAME) mocha --reporter mocha-junit-reporter -t 30000 --exit --recursive ./build/test/api
    displayName: "Running mocha test"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/test-results.xml"

  - script: NODE_ENV=test LOG_LEVEL=debug DB_PWD=$(DB_PASSWORD) DB_USER=$(DB_USERNAME) DB_HOST=$(DB_HOST) DB_NAME=$(DB_NAME) nyc --reporter cobertura mocha --reporter mocha-junit-reporter -t 30000 --exit --recursive ./build/test/api
    displayName: "Running test coverage"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(Build.SourcesDirectory)/**/*coverage.xml"
